version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_DB: bootcamp_db
      POSTGRES_USER: bootcamp_user
      POSTGRES_PASSWORD: bootcamp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
